[tool.briefcase]
project_name = "Picker"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/picker"
license = "BSD license"
author = 'Marcus Kok'
author_email = "mskok@ncsu.edu"

[tool.briefcase.app.picker]
formal_name = "Picker"
description = "Python picker app"
icon = "src/picker/resources/picker"
sources = ['src/picker']
requires = []


[tool.briefcase.app.picker.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.picker.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.picker.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.picker.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.picker.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
